name: deep_learning
channels:
  - defaults
dependencies:
  - scikit-learn=0.22.1
  - pillow=7.0.0
  - scipy=1.4.1
  - numpy=1.18.1
  - python=3.7
  - h5py=2.10.0
  - matplotlib=3.1.3
  - pip
  - pip:
    - tensorflow==2.1
    - tensorboard==2.1
